import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from '../components/Layout'
import Draw from '../components/Draw'
import {lines} from '../public/lines'
type Line = { x: number; y: number }[];

function resizeLines (lines: Line[]): Line[] {
    return lines.map((line) => {
        return line.map((point) => {
        return {
            x: point.x + 150,
            y: point.y + 150,
        }
        })
    })
}

const Home: NextPage = () => {

    console.log('Data', resizeLines(lines));
    console.log('Data2', lines);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Draw data={resizeLines(lines)} />
      </Layout>
    </div>
  )
}

export default Home