import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/Layout'
import CityTempChart from '../components/CityTempChart'

export default function VisxTesting() {

    return (
        <div style={{height: "1000px", padding: '0 40px'}}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <CityTempChart />
            </Layout>
        </div>
    )
}
